services:
  inventory-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d inventory"]
      interval: 5s
      retries: 5
  payment-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d payments"]
      interval: 5s
      retries: 5
  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orders"]
      interval: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
  inventory-service:
    build: ./inventory-service
    ports:
      - "8001:8000"
    depends_on:
      inventory-db:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://user:password@inventory-db:5432/inventory
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SERVICE_NAME: inventory-service
  payment-service:
    build: ./payment-service
    ports:
      - "8002:8000"
    depends_on:
      payment-db:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://user:password@payment-db:5432/payments
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SERVICE_NAME: payment-service
  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
    depends_on:
      order-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      payment-service:
        condition: service_started
      inventory-service:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://user:password@order-db:5432/orders
      PAYMENT_SERVICE_URL: http://payment-service:8000
      INVENTORY_SERVICE_URL: http://inventory-service:8000
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_SERVICE_NAME: order-service
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order-service
