events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=order_limit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    server {
        listen 80;

        location / {
            limit_req zone=order_limit burst=20 nodelay;
            limit_conn conn_limit 10;

            proxy_pass http://order-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
